### ISSUE TITLE
Credit

### ISSUE THREAD

**Issue by r-barnes** [skeeto/optparse#6]
I'm glad this library exists, and I'm about to use it in a project.

I wonder if you'd be alright with adding your name, or a link to this Github repo somewhere in the credit file? In case someone ever asks me where a piece of code is from, it's nice to be able to point back to its author.

**Comment by skeeto** [comment]
I have no reason at all to object, so, please, credit me however you feel is appropriate. It's in the public domain so that you're not legally obligated to do anything at all, but credit is certainly appreciated. 

If your project is going to be on GitHub, could you share a link to it? I'm always curious how and where Optparse gets used. Thanks!

**Comment by r-barnes** [comment]
Oh, I'd been suggesting that you add a little credit to your file header. I ultimately ended up writing my own option parser that better fit the particulars of my use case.
